export const LOGIN_STARTED = "LOGIN_START";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER_STARTED = "REGISTER_STARTED"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const LOGOUT_STARTED = "LOGOUT_STARTED";
export const LOGOUT_DONE = "LOGOUT_DONE";

export const CHECK_LOGIN_STARTED = "CHECK_LOGIN_STARTED"

export const USER_DETAIL = "USER_DETAIL"
export const USER_DETAIL_FAILED = "USER_DETAIL_FAILED"

export const ADD_LIST_STARTED = "ADD_LIST_STARTED"
export const ADD_LIST_SUCCESSFUL = "ADD_LIST_SUCCESSFUL"
export const ADD_LIST_FAILED = "ADD_LIST_FAILED"

export const DELETE_LIST_STARTED = "DELETE_LIST_STARTED"
export const DELETE_LIST_SUCCESSFUL = "DELETE_LIST_SUCCESSFUL"
export const DELETE_LIST_FAILED = "DELETE_LIST_FAILED"

export const GET_TODO_ITEMS_STARTED = "GET_TODO_ITEMS_STARTED"
export const GET_TODO_ITEMS_SUCCESSFUL = "GET_TODO_ITEMS_SUCCESSFUL"
export const GET_TODO_ITEMS_FAILED = "GET_TODO_ITEMS_FAILED"

export const ADD_TODO_ITEMS_STARTED = "ADD_TODO_ITEMS_STARTED"
export const ADD_TODO_ITEMS_SUCCESSFUL = "ADD_TODO_ITEMS_SUCCESSFUL"
export const ADD_TODO_ITEMS_FAILED = "ADD_TODO_ITEMS_FAILED"

export const GET_TODO_ITEM_STARTED = "GET_TODO_ITEM_STARTED"
export const GET_TODO_ITEM_SUCCESSFUL = "GET_TODO_ITEM_SUCCESSFUL"
export const GET_TODO_ITEM_FAILED = "GET_TODO_ITEM_FAILED"

export const DELETE_ITEM_STARTED = "DELETE_ITEM_STARTED"
export const DELETE_ITEM_SUCCESSFUL = "DELETE_ITEM_SUCCESSFUL"
export const DELETE_ITEM_FAILED = "DELETE_ITEM_FAILED"

export const UPDATE_ITEM_STARTED = "UPDATE_ITEM_STARTED"
export const UPDATE_ITEM_SUCCESSFUL = "UPDATE_ITEM_SUCCESSFUL"
export const UPDATE_ITEM_FAILED = "UPDATE_ITEM_FAILED"

export const ADD_DEPENDENCY_STARTED = "ADD_DEPENDENCY_STARTED"
export const ADD_DEPENDENCY_FAILED = "ADD_DEPENDENCY_FAILED"
export const ADD_DEPENDENCY_SUCCESSFUL = "ADD_DEPENDENCY_SUCCESSFUL"

export const REMOVE_DEPENDENCY_STARTED = "REMOVE_DEPENDENCY_STARTED"
export const REMOVE_DEPENDENCY_FAILED = "REMOVE_DEPENDENCY_FAILED"
export const REMOVE_DEPENDENCY_SUCCESSFUL = "REMOVE_DEPENDENCY_SUCCESSFUL"

export const UPDATE_STATUS_STARTED = "UPDATE_STATUS_STARTED"
export const UPDATE_STATUS_FAILED = "UPDATE_STATUS_FAILED"
export const UPDATE_STATUS_SUCCESSFUL = "UPDATE_STATUS_SUCCESSFUL"

export const FILTER_ORDER_SUCCESSFUL = "FILTER_ORDER_SUCCESSFUL"
export const CLEAR_FILTERS_ORDERS = "CLEAR_FILTERS_ORDERS"

